### ISSUE TITLE
ESLint doesn't work with flat config

### ISSUE THREAD

**Issue by TiroZit** [ModyQyW/vite-plugin-eslint2#36]
### Describe the bug

ESLint introduced a new configuration format eslint.config.js (flat config). With the new format, an error is thrown when starting the application:
```
node:internal/event_target:1012
  process.nextTick(() => { throw err; });
                           ^
Error: No ESLint configuration found in \src\stories\_utils\docs.
    at CascadingConfigArrayFactory._finalizeConfigArray (\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3977:19)
    at CascadingConfigArrayFactory.getConfigArrayForFile (\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3768:21)
    at FileEnumerator._iterateFilesRecursive (\node_modules\eslint\lib\cli-engine\file-enumerator.js:473:52)
    at _iterateFilesRecursive.next (<anonymous>)
    at FileEnumerator._iterateFilesRecursive (\node_modules\eslint\lib\cli-engine\file-enumerator.js:495:33)
    at _iterateFilesRecursive.next (<anonymous>)
    at FileEnumerator._iterateFilesRecursive (\node_modules\eslint\lib\cli-engine\file-enumerator.js:495:33)
    at _iterateFilesRecursive.next (<anonymous>)
    at FileEnumerator._iterateFilesRecursive (\node_modules\eslint\lib\cli-engine\file-enumerator.js:495:33)
    at _iterateFilesRecursive.next (<anonymous>)
Emitted 'error' event on Worker instance at:
    at [kOnErrorMessage] (node:internal/worker:300:10)
    at [kOnMessage] (node:internal/worker:311:37)
    at MessagePort.<anonymous> (node:internal/worker:212:57)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:737:20)
    at exports.emitMessage (node:internal/per_context/messageport:23:28)
    at [kOnExit] (node:internal/worker:278:5)
    at Worker.<computed>.onexit (node:internal/worker:209:20) {
  messageTemplate: 'no-config-found',
  messageData: {
    directoryPath: 'src\\stories\\_utils\\docs'
  }
```

Running ESLint directly via CLI works with the new config. The checker plugin worked properly before migrating to the new ESLint config.

### Expected behavior
ESLint should run without an error and the `eslint.config.js` file should be used.

The ESLint class used by this plugin doesn't support the new flat config. For the flat config the FlatESLint class must be used which is only exported via eslint/use-at-your-own-risk entrypoint: https://eslint.org/blog/2022/08/new-config-system-part-3/#using-flat-config-with-the-eslint-class

**Comment by ModyQyW** [comment]
Sorry that I missed your issue because I have too many emails. 🙏

It will be nice to support the flat config! But I think it is kind of hard to determine which class to use. I think maybe a pre-scan will be nice. What do you think? @TiroZit

**Comment by TiroZit** [comment]
> Sorry that I missed your issue because I have too many emails. 🙏
> 
> It will be nice to support the flat config! But I think it is kind of hard to determine which class to use. I think maybe a pre-scan will be nice. What do you think? @TiroZit 

I honestly don't know the best way to implement this, but pre scan sounds nice. @ModyQyW

**Comment by ModyQyW** [comment]
Hi @TiroZit .

After reading related blogs and docs(like https://eslint.org/blog/2022/08/new-config-system-part-3/#using-flat-config-with-the-eslint-class, https://eslint.org/blog/2023/10/flat-config-rollout-plans/#main, https://eslint.org/docs/latest/use/configure/configuration-files-new), I find it much more complex than I think. 

I simply fine-tuned the plugin implementation to reduce complexity and avoid more black boxes to support the flat config system. Hope you can enjoy.

In vite-plugin-eslint2@^4.2.0 and eslint@8 (which supports the flat config system, and the higher the better), set `eslintPath` to `'eslint/use-at-your-own-risk'` and place an `eslint.config.js` file in the root of your project, then everything should work.

Tell me if something is wrong. Thanks.

**Comment by TiroZit** [comment]
> Hi @TiroZit .
> 
> After reading related blogs and docs(like https://eslint.org/blog/2022/08/new-config-system-part-3/#using-flat-config-with-the-eslint-class, https://eslint.org/blog/2023/10/flat-config-rollout-plans/#main, https://eslint.org/docs/latest/use/configure/configuration-files-new), I find it much more complex than I think.
> 
> I simply fine-tuned the plugin implementation to reduce complexity and avoid more black boxes to support the flat config system. Hope you can enjoy.
> 
> In vite-plugin-eslint2@^4.2.0 and eslint@8 (which supports the flat config system, and the higher the better), set `eslintPath` to `'eslint/use-at-your-own-risk'` and place an `eslint.config.js` file in the root of your project, then everything should work.
> 
> Tell me if something is wrong. Thanks.

Hi @ModyQyW .

The solution is working, thank you for the prompt fix. However, I've discovered a bug. When ESLint identifies an error and you correct it, then save the file, the error in the development environment doesn't disappear. This happens despite the fact that the error has been resolved and no longer exists in the code.

I'm using [eslint config](https://github.com/antfu/eslint-config) by Antfu

**Comment by ModyQyW** [comment]
Are you facing this problem? I am kind of not sure. Try to enable `lintOnStart` option if you are facing this problem.

<img width="684" alt="image" src="https://github.com/ModyQyW/vite-plugin-eslint2/assets/31850793/e1620567-e9fb-4ec7-934a-88661b8019fd">

Please open another issue and provide a repo if you are not facing this problem. Thanks! 🙏

**Comment by ModyQyW** [comment]
Hi @TiroZit . Please let me know if it helps. Thanks.

> Are you facing this problem? I am kind of not sure. Try to enable `lintOnStart` option if you are facing this problem.
> 
> <img alt="image" width="684" src="https://user-images.githubusercontent.com/31850793/277205900-e1620567-e9fb-4ec7-934a-88661b8019fd.png">
> Please open another issue and provide a repo if you are not facing this problem. Thanks! 🙏

**Comment by ModyQyW** [comment]
I am closing this issue since there are no responses. Feel free to open a new one. Thank you.
