### ISSUE TITLE
fix option is not documented

### ISSUE THREAD

**Issue by mrleblanc101** [ModyQyW/vite-plugin-eslint2#37]
I'm moving from vite-eslint-plugin and I was looking at the options wondering where the `fix` option was. Found it in the exemple, but it's not documented under `options`

**Comment by ModyQyW** [comment]
@mrleblanc101 Sorry for my delay.

The `fix` option is included in [ESLint Node.js API constructor options](https://eslint.org/docs/developer-guide/nodejs-api#-new-eslintoptions), which is shown above the `fix` example.

Check https://github.com/ModyQyW/vite-plugin-eslint2#options.

**Comment by mrleblanc101** [comment]
I guess I was more looking for something like the other options, with name, type, default, description
