### ISSUE TITLE
@types/eslint should not be a required peer dependency

### ISSUE THREAD

**Issue by chawes13** [ModyQyW/vite-plugin-eslint2#38]
### Describe the bug

When installing `vite-plugin-eslint2` into a Vite app based on a template that does not use TypeScript, there is a console warning about `@types/eslint` having an unmet peer dependency.
```
vite-plugin-eslint2@4.4.0" has unmet peer dependency "@types/eslint@^7.0.0 || ^8.0.0 || ^9.0.0-0".
```

### Reproduction

URL: https://stackblitz.com/edit/vitejs-vite-z2vocr?file=package-lock.json

Steps:
1. Run ` yarn install --force`

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.20.3 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 10.2.3 - /usr/local/bin/npm
    pnpm: 8.15.6 - /usr/local/bin/pnpm
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ModyQyW/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ModyQyW** [comment]
I've already stated in the README that you should install @types/eslint. without it, projects using TypeScript may experience unexpected conditions, while projects using JavaScript should have no effect. Warnings within the terminal aside, can you tell me what you're actually experiencing?

**Comment by chawes13** [comment]
It's just the warning in the terminal – functionality works great (thank you!).

The reason why I raised this is because it does seem atypical for a package to require the types as a peer dependency, so I'm more curious than anything. E.g., https://github.com/facebook/react, https://github.com/expressjs/express/blob/master/package.json.

If it's recommended, then should it be declared as optional (similar to rollup)?

**Comment by ModyQyW** [comment]
What you say makes a lot of sense. I'll update and release a new version as soon as I get through this tough overtime period. Thanks again for your suggestions. 🙏

**Comment by ModyQyW** [comment]
Just publish v4.4.1 to focus on this problem. Please let me know if anything wrong.
